### ISSUE TITLE
Lack of the files of language/translation?

### ISSUE THREAD

**Issue by jeffminim** [sdkng44/dota2-match-history-parser#1]
After selecting the language, any of them:

? Select your language: 中文
[
  [Error: ENOENT: no such file or directory, open './locales/zh/translation.json'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: './locales/zh/translation.json'
  },
  [Error: ENOENT: no such file or directory, open './locales/en/translation.json'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: './locales/en/translation.json'
  }
]

**Comment by sdkng44** [comment]
Hello, it seems that the folder "./locales/..." was not uploaded, I've just added "./locales/..." to the repository, now it should work fine!

Please could you clone again the repository? This time it should successfully download the full files.

Also if you dont want to delete your folder and clone it again, you can locate yourself in the folder of "dota2-match-details-parser" that you already downloaded and open a CMD or Powershell and type "git pull origin main", that should download the last files.

![image](https://github.com/user-attachments/assets/b74437c6-53c8-4261-8201-190e0f6ba38d)

![image](https://github.com/user-attachments/assets/964ca2f5-c716-4f1c-8203-a5beb0204180)



Please confirm if you were able to download the complete files to verify that there are no more problems, thanks!

**Comment by sdkng44** [comment]
Closing this issue as solved.
